version: 2.1


jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/node:14.15.3-browsers
    steps:
      - checkout
      - run: yarn set version berry
      - run: yarn install --immutable --immutable-cache
      - run: yarn check:deps
      - run: yarn check:lint
      - run: yarn check:csslint
      - run: yarn check:pretty
      - run: yarn check:test
      - run: yarn check:e2e
      - run: yarn build
